### ISSUE TITLE
Transform Google format into friendlier common format

### ISSUE THREAD

**Issue by konklone** [18F/analytics-proxy-nodejs#9]
We should use a provider-agnostic format, and something we're fine with people downloading and starting to potentially write code against.

[Gov.UK's schema](https://www.performance.service.gov.uk/data/govuk/visitors?duration=104&collect=visitors%3Asum&group_by=website&period=week) is cleaner than Google's, but aesthetically, I'm not a fan of the underscore prefixes and colons. 

The schema may vary for different metrics. For weekly visitors, how about:

```json
{
  "name": "weekly_visitors",
  "site": "all",
  "description:": "Weekly visitors to all .gov sites tracked by the U.S. federal government's Digital Analytics Program.",
  "documentation": "http://www.usa.gov/performance",
  "data": [
    {
      "date": "2014-12-22",
      "visitors": 2340123
    },
    {
      "date": "2014-12-23",
      "visitors": 2045623
    }
  ],
  "totals": {
    "start_date": "2014-12-22",
    "end_date": "2014-12-23",
    "visitors": 4385746
  }
}
```

Thoughts?

**Comment by adelevie** [comment]
I haven't written much/anything that consumes analytics data, so take this with a grain of salt: looks good to me.

**Comment by konklone** [comment]
This would also make the report format we use in `reports.json` have to become something like this:

```json

{
  "reports": [
    {
      "name": "weekly-users",
      "query": {
        "dimensions": "ga:dayOfWeekName,ga:date",
        "metrics": "ga:users",
        "start-date" : "8daysAgo",
        "end-date" : "yesterday"
      },
      "meta": {
        "site": "all",
        "description:": "Weekly visitors to all .gov sites tracked by the U.S. federal government's Digital Analytics Program.",
        "documentation": "http://www.usa.gov/performance",
      }
    }
  ]
}
```

**Comment by jackiekazil** [comment]
:+1:
